/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import BLL.InventoryDetailBLL;
import DTO.InventoryDetail;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.plaf.TableUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nam
 */
public class ChiTietKiemKe extends javax.swing.JPanel {
    public static int currentIdInventory;
    public static int currentIdRegister;
//    FormatTable formatTable = new FormatTable();
    InventoryDetailBLL bus = new InventoryDetailBLL();
    DefaultTableModel model =new DefaultTableModel();
    /**
     * Creates new form EmployeePanel
     */
    public ChiTietKiemKe() {
        initComponents();
        init();
//        Count.setText(demso().toString());
    }
    
    
    public void init()
    {
//        formatTable.formatTablenoIcon(table);
        
        //Header content of jtable
        bus.docInventory();
        Vector header = new Vector();
        header.add("ID");
        header.add("IdRegister");
        header.add("IdInventory");
        header.add("isReading");
        
        if (model.getRowCount()==0)
        { 
                model=new DefaultTableModel(header,0){
                @Override//No edit
                public boolean isCellEditable(int row, int column) 
                {          
                    if(column == 4)
                    {
                        return true;
                    } else {
                        return false;
                    }
                }
            };
        } 
        
        table.setModel(model);
        docInvntoryDetail();
        
        //format table
        
        
        table.getColumnModel().getColumn(0).setPreferredWidth(120);
        table.getColumnModel().getColumn(1).setPreferredWidth(120);
        table.getColumnModel().getColumn(2).setPreferredWidth(120);
        table.getColumnModel().getColumn(3).setPreferredWidth(120);


        
    }
    
    public void refresh()
    {
        init();
        
    }
    
    public void docInvntoryDetail()
    {
        try
        {
            int rowCount = model.getRowCount();//remove all row
            for (int i = rowCount - 1; i >= 0; i--) 
            {
                model.removeRow(i);
            }
            for(InventoryDetail idetail : InventoryDetailBLL.sumArr)
            {
                Vector row = new Vector();
                row.add(idetail.getId());
                row.add(idetail.getIdRegister());
                row.add(idetail.getIdInventory());
                row.add(idetail.getIsReading());
                                
                
                model.addRow(row);
            }
            table.setModel(model);
            
            
            
            
           
        
        } catch(Exception e) {
            System.out.println("Lỗi GUI");
        }
    }
    
    public int demso()
    {
        int rowCountne=table.getRowCount();
            
            
            int dem=0;
            for (int row=0; row<table.getRowCount(); row++)
            {
                
                if(table.getValueAt(row, 3).equals(0))
                {
                    dem++;
                }
            }
            return dem;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Count = new javax.swing.JLabel();
        DemSo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setFillsViewportHeight(true);
        table.setName(""); // NOI18N
        table.setShowVerticalLines(false);
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 740, 330));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-user-menu-male-30.png"))); // NOI18N
        jLabel1.setText("Bảng chi tiết thông tin kiểm kê");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel1.add(Count, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 70, 30));

        DemSo.setText("KiemTra");
        DemSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemSoActionPerformed(evt);
            }
        });
        jPanel1.add(DemSo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 131, 780, 460));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 780, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Chi Tiết Phiếu Kiểm Kê");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        OverrallFrame.changeMainInfo(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DemSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemSoActionPerformed
        // TODO add your handling code here:
        if(demso()>0)
        {
            JOptionPane.showMessageDialog(null, "Thieu "+demso()+" San pham");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Day Du");
        }
    }//GEN-LAST:event_DemSoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Count;
    private javax.swing.JButton DemSo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
